
services:
  mysqldb:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: klustudentdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-mysql-net

  backend:
    image: deekshith1809/artgallery-backend:latest   # ✅ Ensure this image is built & pushed correctly
    container_name: springboot
    ports:
      - "2025:2000"  # Expose backend on localhost:2025
    depends_on:
      - mysqldb
    restart: on-failure
    networks:
      - springboot-mysql-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/klustudentdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: docker

  frontend:
    image: deekshith1809/artgallery-frontend:latest   # ✅ Ensure this image is built & pushed correctly
    container_name: react
    ports:
      - "3000:80"  # Expose frontend on localhost:3000
    depends_on:
      - backend
    restart: on-failure
    networks:
      - springboot-mysql-net

volumes:
  mysql_data:

networks:
  springboot-mysql-net:
    driver: bridge
